--ECHOES OF WHIMSY HEROKU/POSTGRESQL SQL:

CREATE TYPE securityLevel as ENUM('1','2','3');
CREATE TYPE attribType as ENUM('XP','LVL');
CREATE TYPE modType as ENUM('+', 'x');

CREATE TABLE public.users (
	userID BIGSERIAL NOT NULL PRIMARY KEY,	
	userEmail VARCHAR(50) NOT NULL UNIQUE,
	userHashPass VARCHAR(255) NOT NULL,
	userName VARCHAR(50) NOT NULL UNIQUE,
	userFName VARCHAR(50) NOT NULL,
	userLName VARCHAR(50) NOT NULL,
	userLevel securityLevel NOT NULL DEFAULT '1',
	userDisabled BOOLEAN NOT NULL DEFAULT false,
	userSuspended  BOOLEAN NOT NULL DEFAULT false,
	userEmailVerified BOOLEAN NOT NULL DEFAULT false,
	sessionHashPass VARCHAR(255) NOT NULL,
	lastActive timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.txRace (
	txRaceID SERIAL NOT NULL PRIMARY KEY,
	txRaceName VARCHAR(100) NOT NULL,
	txRacePron VARCHAR(30),
	txRaceDesc VARCHAR(150)
);

CREATE TABLE public.txFamily (
	txFamilyID SERIAL NOT NULL PRIMARY KEY,
	txFamilyName VARCHAR(100) NOT NULL,
	txFamilyPron VARCHAR(30),
	txFamilyDesc VARCHAR(150),
	txRaceID INT NOT NULL REFERENCES public.txRace(txRaceID)
);

CREATE TABLE public.txGenus (
	txGenusID SERIAL NOT NULL PRIMARY KEY,
	txGenusName VARCHAR(100) NOT NULL,
	txGenusPron VARCHAR(30),
	txGenusDesc VARCHAR(150),
	txFamilyID INT NOT NULL REFERENCES public.txFamily(txFamilyID)
);

CREATE TABLE public.char (
	charID BIGSERIAL NOT NULL PRIMARY KEY,
	userID BIGINT NOT NULL REFERENCES public.users(userID),
	charName VARCHAR(100) NOT NULL,
	txGenusID INT NOT NULL REFERENCES public.txGenus(txGenusID),
	CONSTRAINT U_charID_userID UNIQUE (charID, userID)
);

CREATE TABLE public.attrib (
	attribID SMALLSERIAL NOT NULL PRIMARY KEY,
	attribName VARCHAR(100) NOT NULL,
	attribTypeOf attribType NOT NULL DEFAULT 'XP'
);

CREATE TABLE public.modifiers (
	modID SMALLSERIAL NOT NULL PRIMARY KEY,
	modName  VARCHAR(100) NOT NULL
);

CREATE TABLE public.skill (
	skillID SERIAL NOT NULL PRIMARY KEY,
	skillName VARCHAR(100) NOT NULL,
	skillDescShort VARCHAR(100) NOT NULL,
	skillDescLong TEXT NOT NULL
);

CREATE TABLE public.item (
	itemID SERIAL NOT NULL PRIMARY KEY,
	itemName VARCHAR(100) NOT NULL,
	itemDescShort VARCHAR(100) NOT NULL,
	itemDescLong TEXT NOT NULL
);

CREATE TABLE public.charAttrib (
	charAttribID BIGSERIAL NOT NULL PRIMARY KEY,
	charID BIGINT NOT NULL REFERENCES public.char(charID),
	attribID SMALLINT NOT NULL REFERENCES public.attrib(attribID),
	charAttribVal BIGINT NOT NULL DEFAULT 0,
	CONSTRAINT U_charID_attribID UNIQUE (charID, attribID)
);

CREATE TABLE public.charSkill (
	charSkillID BIGSERIAL NOT NULL PRIMARY KEY,
	charID BIGINT NOT NULL REFERENCES public.char(charID),
	skillID INT NOT NULL REFERENCES public.skill(skillID),
	charSkillXP BIGINT NOT NULL DEFAULT 0,
	CONSTRAINT U_charID_skillID UNIQUE (charID, skillID)
);

CREATE TABLE public.charInv (
	charInvID BIGSERIAL NOT NULL PRIMARY KEY,
	charID BIGINT NOT NULL REFERENCES public.char(charID),
	itemID INT NOT NULL REFERENCES public.item(itemID),
	charInvSlot INT NOT NULL,
	charInvQty SMALLINT NOT NULL DEFAULT 0,
	charInvDur INT NOT NULL DEFAULT 0,
	CONSTRAINT U_charID_charInvSlot UNIQUE (charID, charInvSlot)
);

CREATE TABLE public.skillEff (
	skillEffID BIGSERIAL NOT NULL PRIMARY KEY,
	skillEffName VARCHAR(100) NOT NULL,
	skillEffDescShort VARCHAR(100) NOT NULL,
	skillEffDescLong TEXT NOT NULL,
	modID SMALLINT NOT NULL REFERENCES public.modifiers(modID),
	modTypeOf modType NOT NULL DEFAULT '+',
	modVal BIGINT NOT NULL DEFAULT 0,
	CONSTRAINT U_skillEffID_modID UNIQUE (skillEffID, modID)
);

CREATE TABLE public.itemEff (
	itemEffID BIGSERIAL NOT NULL PRIMARY KEY,
	itemEffName VARCHAR(100) NOT NULL,
	itemEffDescShort VARCHAR(100) NOT NULL,
	itemEffDescLong TEXT NOT NULL,
	modID SMALLINT NOT NULL REFERENCES public.modifiers(modID),
	modTypeOf modType NOT NULL DEFAULT '+',
	modVal BIGINT NOT NULL DEFAULT 0,
	CONSTRAINT U_itemEffID_modID UNIQUE (itemEffID, modID)
);

INSERT INTO public.txrace (txRaceName, txRacePron, txRaceDesc) VALUES
('Crown', NULL, 'Crown Races'),
('Baku', NULL, 'Companion Races'),
('Val''asur', NULL, 'Sovereign Races'),
('Eidolon', NULL, 'Conceptual Races'),
('Ancillary', NULL, 'Ancillary Races');

INSERT INTO public.txfamily (txFamilyName, txFamilyPron, txFamilyDesc, txRaceID) VALUES
('Anchu', NULL, 'Fish Peoples', 1),
('Aran', NULL, 'Arachnid* Peoples', 1),
('Daemon', NULL, 'Infernal Beings', 4),
('Dokkandru', '(Pron.: Doe-kahn-drew)', 'Guardians/Natural Gods/Spirits', 3),
('Eld''rn', NULL, 'Eldritch/Elder Gods/Great Old Ones', 4),
('El''efren', '(Pron.: L-f-wren) \r\n', 'Elementals', 3),
('Ewos', NULL, 'Celestial Beings', 4),
('Fae', NULL, 'Faerie Peoples / God of Dreams', 5),
('Koda', NULL, 'Mammalian Peoples', 1),
('Langol', NULL, 'Crustacean Peoples', 1),
('N''dulate', NULL, 'Cephalopod Peoples', 1),
('N''garra', NULL, 'Reptilian Peoples', 1),
('Nubu', NULL, 'Avian Peoples', 1),
('N''yani', NULL, 'Amphibian Peoples', 1),
('Yama', NULL, 'Insect Peoples', 1),
('Infermut', NULL, 'Fire Wings', 3),
('Efrit', NULL, 'Efrit/Djinn/Genies', 3);

INSERT INTO public.txgenus (txGenusName, txGenusPron, txGenusDesc, txFamilyID) VALUES
('Anakari', '(Pron.: On-car-ee)', 'Raptors and Scavengers, Vultures, Secretary Bird', 13),
('Oku', '(Pron.: Oh-coo)', 'Owls', 13),
('Fataru', '(Pron.: Faw-tar-oo)', 'Fishers, Puffins, Ibis, Flamingo, and Boobies', 13),
('Burvig', '(Pron.: Burr-vig)', 'Mandarin, Bufflehead, Ducks, Geese, Swans, Pelicans', 13),
('Parro', '(Pron.: Paw-row)', 'Grain, Fruit, and Insect Eaters, Parrots, Toucans, Tits, Woodpeckers, Swallows, Hummingbirds, Jays', 13),
('Tuguai', '(Pron.: Two-gg-why)', 'Turkeys, Chickens, Quail, Pheasant, Roadrunner, Kiwi, Ostrich', 13),
('Garra', '(Pron.: Gar-uh)', 'Lizards', 12),
('Leiflids', '(Pron.: Leaf-lid)', 'Geckos', 12),
('Gemmel', '(Pron.: Gem-ll)', ' Skinks', 12),
('Grokarra', '(Pron.: Grow-car-uh)', ' Crocodiles', 12),
('Tsutsuren', '(Pron.: Sue-Sue-ren)', ' Snakes', 12),
('Tsumari', '(Pron.: Sue-mar-ee)', ' Turtles', 12),
('Lamaan', '(Pron.: La-mon)', ' Salamanders and Newts', 14),
('Chr''upp', '(Pron.: Ch-er-up)', ' Frogs and Toads', 14),
('Baas', '(Pron.: Ba-zz)', ' Blindworms/Caecilians', 14),
('Musteleph', '(Pron.: Moose-tell-F)', ' Badgers,  Weasels, Otters, Ferrets, Red Panda, Martens, Minks, Wolverines, Grison, Pole Cats, Skunks, and Stink Badgers', 9),
('Miyat', '(Pron.: Me-yat)', ' Cats, Ocelots, Lions, Tigers, Panthers, Snow-Leopards, Saber-toothed Cats, Genets', 9),
('Usa', '(Pron.: Oo-suh)', ' Bears, Polar, Spectacle, Grizzlies', 9),
('Kité', '(Pron.: Key-tay)', ' Foxes, Fennec Foxes', 9),
('Rhashang', '(Pron.: Raw-sh-on-gg)', ' Wolves', 9),
('Waraabe', '(Pron.: War-ah-bay)', ' Hyenas', 9),
('Baven', '(Pron.: Baa-vv-en)', ' Rodents, Rats, Mice, Chipmunks, Chinchilla, Squirrel, Beavers', 9),
('Akashi', '(Pron.: Ah-kaw-she)', ' Rabbits', 9),
('Horg', '(Pron.: Whore-gg)', ' Pigs', 9),
('Panangu', '(Pron.: Pan-on-goo)', ' Anteaters, Tamadua, Pangolins', 9),
('Nakoza', '(Pron.: Nn-uh-co-zz-uh)', ' Cervidae, Deer, Antilope, Moose, Caribou, Elk', 9),
('Mogwa', '(Pron.: Maw-gg-ww-aa)', ' Bats', 9),
('Mangrol', '(Pron.: Man-grow-ll)', ' Primates', 9),
('Rh''orc', '(Pron.: Roar-kk)', ' Rhinos, Cows, Horses, Etc', 9),
('Vora Pora', '(Pron.: Vv-or-ah Pp-or-ah)', ' Vespids, Flying Scorpion, Tarantula Hawk, Ants', 15),
('Beleg', '(Pron.: Bell-leg)', ' Beetles, Thorn Bug, Roaches, etc', 15),
('As''tas', '(Pron.: Ah-st-uh-ss)', ' Butterflies and Moths, Hickory Horned Devil (Caterpillars)', 15),
('Rhanea', '(Pron.: Raw-nay-ah)', ' Spiders, Black Widow, Jumping Spider, Bunny Harvestmen', 2),
('Saryx', '(Pron.: Ss-air-ick-ss)', ' Scorpions', 2),
('Nhilim', '(Pron.: Knee-limb)', ' Centipedes, Remipedes', 2),
('Tibur', '(Pron.: Tie-burr)', ' Sharks, Swordfish, Sawfish', 1),
('Thres', '(Pron.: Th-re-ss)', ' Skates, Rays', 1),
('Tsural', '(Pron.: Sue-rawl)', ' Eels', 1),
('Apua', '(Pron.: Ah-poo-ah)', ' Riverfish, Longfish,  Arapaima, Barracuda', 1),
('Nuku', '(Pron.: New-ck-oo)', ' Warfish, Spinyfish, Lionfish, Puffers', 1),
('Paku', '(Pron.: Paw-ck-oo)', ' Roundhead, Tang, Triggerfish, Angelfish, Goldfish, Oscar, Piranha', 1),
('Gili', '(Pron.: Gg-ee-ll-ee)', ' Lobsters, shrimp', 10),
('Krahl', '(Pron.: Crawl)', ' Crabs', 10),
('Niivn', '(Pron.: Niv-en)', ' Lice, Whale lice, Isopods, Giant Isopods, Copepods', 10),
('Ouki', '(Pron.: Ow-key)', ' Octopi', 11),
('Iki', '(Pron.: Ee-key)', ' Squid, Cuttlefish', 11),
('Ahkun', '(Pron.: Ah-coon)', ' Nautilus', 11),
('Volkir', '(Pron.: Vol-ck-ee-rr)', ' Fire Elementals', 6),
('Fré', '(Pron.: Fray)', ' Ice Elementals', 6),
('Likwi', '(Pron.: Leak-we)', ' Water Elementals', 6),
('Blüstraan', '(Pron.: Blue-straw-nn)', ' Wind Elementals', 6),
('Rouk', '(Pron.: Row-ck)', ' Earth Elementals', 6),
('Ismut', '(Pron.: Ee-ss-mut)', ' Dragons - Inner fire', 16),
('Fenke', '(Pron.: Fenn-kk)', ' Fenke: Phoenix - Outer fire\r\n\r', 16),
('Daewos', '(Pron.: Day-woe-ss)', ' Deities - Worship, Reverence', 7),
('Isteni', '(Pron.: I-ss-ten-ee)', ' Angels - Hope', 7),
('Daeva', '(Pron.: Day-vv-uh)', ' Devils - Sin', 3),
('Osore', '(Pron.: Oh-sore-ay)', ' Demons - Fear', 3),
('Xychtnyr', '(Pron.: Zz-ick-tt-near)', ' The Incomprehensible', 5),
('Tchkl''nuv', '(Pron.: Shoe-ck-la-new-vv)', ' Insanity, Madness, Confusion, The Wild', 5);

SELECT txracename, txracedesc, txfamilyname, txfamilydesc, txgenusname, txgenuspron, txgenusdesc
FROM txrace LEFT JOIN txfamily on txrace.txraceid=txfamily.txraceid
LEFT JOIN txgenus ON txfamily.txfamilyid=txgenus.txfamilyid
ORDER BY txracename, txfamilyname, txgenusname;


--SCHEMA CREATION
CREATE SCHEMA cse341ta04
    AUTHORIZATION qmylazbfcihiry;

GRANT ALL ON SCHEMA test TO PUBLIC;

GRANT ALL ON SCHEMA test TO gmybdgutyhhvkc;


--ADD CONSTRAINTS...
--ALTER TABLE the_table ADD CONSTRAINT constraint_name UNIQUE (thecolumn);
--ALTER TABLE foo ADD UNIQUE (thecolumn, the2ndcolumn...);

--LOOKUP KEYS/CONSTRAINTS
SELECT con.*
       FROM pg_catalog.pg_constraint con
            INNER JOIN pg_catalog.pg_class rel
                       ON rel.oid = con.conrelid
            INNER JOIN pg_catalog.pg_namespace nsp
                       ON nsp.oid = connamespace
       WHERE nsp.nspname = 'public'
             AND rel.relname = 'users';


INSERT INTO 'char' (userid, charname, txgenusid) VALUES
( (SELECT userid FROM users WHERE username='blbaileyiii'), 'Mahershalalhashbaz',(SELECT txgenusid FROM txgenus WHERE txgenusname='Nhilim') ),
( (SELECT userid FROM users WHERE username='blbaileyiii'), 'Takx',(SELECT txgenusid FROM txgenus WHERE txgenusname='Tsumari') ),
( (SELECT userid FROM users WHERE username='blbaileyiii'), 'Draegür',(SELECT txgenusid FROM txgenus WHERE txgenusname='Grokarra') ),
( (SELECT userid FROM users WHERE username='blbaileyiii'), 'Scarabäeus',(SELECT txgenusid FROM txgenus WHERE txgenusname='Beleg') ),
( (SELECT userid FROM users WHERE username='blbaileyiii'), 'Gron Plunderpaw',(SELECT txgenusid FROM txgenus WHERE txgenusname='Waraabe') ),
( (SELECT userid FROM users WHERE username='blbaileyiii'), 'Elsa Rävviskning',(SELECT txgenusid FROM txgenus WHERE txgenusname='Ankari') ),
( (SELECT userid FROM users WHERE username='blbaileyiii'), 'Hayden Frostfire',(SELECT txgenusid FROM txgenus WHERE txgenusname='Usa') ),
( (SELECT userid FROM users WHERE username='blbaileyiii'), 'Lyra Swiftclaw',(SELECT txgenusid FROM txgenus WHERE txgenusname='Miyat') ),
( (SELECT userid FROM users WHERE username='blbaileyiii'), 'Alandra Marquette',(SELECT txgenusid FROM txgenus WHERE txgenusname='Rhanea') ),
( (SELECT userid FROM users WHERE username='blbaileyiii'), 'Kara Emberwind',(SELECT txgenusid FROM txgenus WHERE txgenusname='Lamaan') ),
( (SELECT userid FROM users WHERE username='blbaileyiii'), 'Traaqz',(SELECT txgenusid FROM txgenus WHERE txgenusname='Vora Pora') ),
( (SELECT userid FROM users WHERE username='blbaileyiii'), 'Heavens Song',(SELECT txgenusid FROM txgenus WHERE txgenusname='As''tas') ),
( (SELECT userid FROM users WHERE username='bmwilliamson'), 'Ulipeties Hazzelforth',(SELECT txgenusid FROM txgenus WHERE txgenusname='Oku') ),
( (SELECT userid FROM users WHERE username='bmwilliamson'), 'Neil Toupes',(SELECT txgenusid FROM txgenus WHERE txgenusname='Musteleph') ),
( (SELECT userid FROM users WHERE username='bmwilliamson'), 'Gwottel Seet',(SELECT txgenusid FROM txgenus WHERE txgenusname='Mogwa') ),
( (SELECT userid FROM users WHERE username='bmwilliamson'), 'Lamerah Hep',(SELECT txgenusid FROM txgenus WHERE txgenusname='Rh''orc') ),
( (SELECT userid FROM users WHERE username='sebailey'), 'Harlow Wells',(SELECT txgenusid FROM txgenus WHERE txgenusname='Kité') ),
( (SELECT userid FROM users WHERE username='sebailey'), 'Annalise Victor',(SELECT txgenusid FROM txgenus WHERE txgenusname='Tsutsuren') ),
( (SELECT userid FROM users WHERE username='sebailey'), 'Tallulah',(SELECT txgenusid FROM txgenus WHERE txgenusname='Miyat') ),
( (SELECT userid FROM users WHERE username='gberguson'), 'Worg Ballisade',(SELECT txgenusid FROM txgenus WHERE txgenusname='Rhashang') ),
( (SELECT userid FROM users WHERE username='gberguson'), 'Tsumal',(SELECT txgenusid FROM txgenus WHERE txgenusname='Tsumari') ),
( (SELECT userid FROM users WHERE username='gberguson'), 'Mr. Chapps',(SELECT txgenusid FROM txgenus WHERE txgenusname='Fataru') ),
( (SELECT userid FROM users WHERE username='jskidmore'), 'Wyatt Erp',(SELECT txgenusid FROM txgenus WHERE txgenusname='Chr''upp') ),
( (SELECT userid FROM users WHERE username='jskidmore'), 'Sticky Licky',(SELECT txgenusid FROM txgenus WHERE txgenusname='Panangu') ),
( (SELECT userid FROM users WHERE username='ltonnies'), 'Lance Tonnes',(SELECT txgenusid FROM txgenus WHERE txgenusname='Tibur') );


INSERT INTO attrib (attribname, attribtypeof) VALUES
('NO_CON', 'NO'),
('NO_MAL', 'NO'),
('NO_BAC', 'NO'),
('DT_RST', 'DT'),
('XP_STR', 'XP'),
('XP_DEX', 'XP'),
('XP_AGL', 'XP'),
('XP_END', 'XP'),
('XP_INT', 'XP'),
('XP_WLP', 'XP'),
('XP_PER', 'XP'),
('XP_LCK', 'XP'),
('XP_CHA', 'XP');


INSERT INTO item (itemname, itemdescshort, itemdesclong) VALUES
('Ruran''s Eyewear','Head Armor','Ruran was a decent practitioner of Illusions and Hypnotism. Unfortunately, he also frequently lost his glasses.'),
('Glyph Robes','Chest Armor',' Advanced Mage Robes'),
('Jewel Wand','One-handed Weapon','Advanced Mage Wand'),
('Black Cloak','Back Armor','A standard black cloak.'),
('Hulan''s Serrated Blade','Two-Handed Weapon','Hulan the warrior bested many a foe with his great serrated blade. Chance to inflict bleed. +5 to Bleed Duration.'),
('Burgundy Brigadine','Chest Armor','A standard Leather Bridadine dyed burgundy or someone can''t hold their liquor.'),
('Iron Shoulder Pad (Left)','Shoulder Armor','Always in style: one and only one shoulder pad. -Waldo Wiley'),
('Iron Bracers','Arm Armor','Brace your self.'),
('Iron Greaves','Leg Armor','Don''t worry be happy.'),
('Drake Tooth Dagger','One-handed Weapon','A small vein pulses with ambient venom. Chance to inflict poison. +2 Poison Duration.'),
('Midnight Blue Hood','Back Armor','Nothing says, "Don''t notice me," like a hood. -2 Stealth in light. +2 Stealth in shadow.'),
('Black Vestments','Chest Armor','Evil overlord much?'),
('Rapid Fire Crossbow','Two-Handed Weapon','Concealable. Deadly. Loud. -2 Stealth while in use.'),
('Aegis','Off-Hand Weapon','A shield. A big round shield.'),
('Golden Platemail','Chest Armor','Gold isn''t very durable. +1 AC'),
('Golden Bracers','Arm Armor','Gold isn''t very durable. +1 AC'),
('Golden Greaves','Leg Armor','Gold isn''t very durable. +1 AC'),
('Red Cape','Back Armor','No capes. +2 Charisma. -1 AC.'),
('Adament Hammer','Two-Handed Weapon','We''re sure it''s a hammer. Like really sure. Heavy'),
('Mimic','Storage Replacement System','This thing has decided not to eat your stuff. Or you. Both positives.'),
('Leather Grieves','Leg Armor','Sounds like someone doesn''t know what grieves are made out from.'),
('Leather Bracers','Arm Armor','You''re just dying to change the color.'),
('Leather Brigadine','Chest Armor','Just how many hues of brown can their be?'),
('Rampant Migglewog Gambeson','Chest Armor','Someone brought it down. Could someone bring you down?'),
('Leather Cuirass','Chest Armor','It''s buff''d to perfection. +2 AC.'),
('Dark Leather Pauldrons','Shoulder Armor','Sure to win some prizes as this year''s Halloween Competition.'),
('Dark Leather Breastplate','Chest Armor','You feel the darkness surround you.'),
('Leather Lorica Segmenata','Chest Armor','Standard-issue mass-produced soldier''s chest piece.'),
('Zombie Bite Guard','Shoulder Armor','Curiously, they only seem to bite right there.'),
('Fire Warden Robes','Chest Armor','Robes... You know...for...a...fire...warden.'),
('Ember Staff','Two-Handed Weapon','The light is dying. So are your enemies.'),
('Twilight Scythe','Two-Handed Weapon','Someone didn''t fear the reaper.'),
('Reductionist Slime','Gizmo','Double-click to use. Quickly clear away old rubish and possibly get something something for it. Breaks down items and returns a portion of the materials.'),
('Imperial Robe','Back Armor','Well, technically it isn''t just back armor. It covers the front too. But at least everyone will know who''s side you''re on.'),
('Imperial Boots','Foot Armor','Standard-issue mass-produced soldier''s boots.'),
('Solid Leather Boots','Foot Armor','It''s a solid choice for footwear.'),
('Iron Footwear','Foot Armor','Standard Iron Footwear.'),
('Gold Footwear','Foot Armor','Gold isn''t very durable. +1 AC'),
('Iron Long Sword','Two-Handed Weapon','Standard Long Sword.'),
('Aeris','Currency','Copper Coin; 100 Aeris = 1 Argentum'),
('Argentum','Currency','Silver Coin; 100 Argentum = 1 Aurem'),
('Aurem','Currency','Gold Coin; 100 Aurem = 1 Platinum'),
('Platinum','Currency','Platinum Coin'),
('Spine Guard','Back Armor','That thing is important. Guard it.'),
('Walking Staff','Two-Handed Weapon','Typical old person mobility enhancement device. +2 Stamina if stamina is less than 10.'),
('Adventurer''s Essentials Kit','Gizmo','Contains a water skin, a reusable torch, a bedroll, a small tent, a fire striker, flit, etc.'),
('Iron Short Sword','One-handed Weapon','Standard Short Sword. Unless, you are a dwarf. In that case it is probably a regular sword.'),
('Town Map','Gizmo','Double-click to view.'),
('Town Clothes','Town Clothes','These clothes are clean and can be worn anywhere armaments and armor are not allowed.');


INSERT INTO public.charattrib (charid,attribid,charattribval) VALUES
(1, 1, 0),
(1, 2, 0),
(1, 3, 0),
(1, 4, 0),
(1, 5, 0),
(1, 6, 0),
(1, 7, 0),
(1, 8, 0),
(1, 9, 0),
(1, 10, 0),
(1, 11, 0),
(1, 12, 0),
(1, 13, 0),
(2, 1, 0),
(2, 2, 0),
(2, 3, 0),
(2, 4, 0),
(2, 5, 0),
(2, 6, 0),
(2, 7, 0),
(2, 8, 0),
(2, 9, 0),
(2, 10, 0),
(2, 11, 0),
(2, 12, 0),
(2, 13, 0),
(3, 1, 0),
(3, 2, 0),
(3, 3, 0),
(3, 4, 0),
(3, 5, 0),
(3, 6, 0),
(3, 7, 0),
(3, 8, 0),
(3, 9, 0),
(3, 10, 0),
(3, 11, 0),
(3, 12, 0),
(3, 13, 0),
(4, 1, 0),
(4, 2, 0),
(4, 3, 0),
(4, 4, 0),
(4, 5, 0),
(4, 6, 0),
(4, 7, 0),
(4, 8, 0),
(4, 9, 0),
(4, 10, 0),
(4, 11, 0),
(4, 12, 0),
(4, 13, 0),
(5, 1, 0),
(5, 2, 0),
(5, 3, 0),
(5, 4, 0),
(5, 5, 0),
(5, 6, 0),
(5, 7, 0),
(5, 8, 0),
(5, 9, 0),
(5, 10, 0),
(5, 11, 0),
(5, 12, 0),
(5, 13, 0),
(6, 1, 0),
(6, 2, 0),
(6, 3, 0),
(6, 4, 0),
(6, 5, 0),
(6, 6, 0),
(6, 7, 0),
(6, 8, 0),
(6, 9, 0),
(6, 10, 0),
(6, 11, 0),
(6, 12, 0),
(6, 13, 0),
(7, 1, 0),
(7, 2, 0),
(7, 3, 0),
(7, 4, 0),
(7, 5, 0),
(7, 6, 0),
(7, 7, 0),
(7, 8, 0),
(7, 9, 0),
(7, 10, 0),
(7, 11, 0),
(7, 12, 0),
(7, 13, 0),
(8, 1, 0),
(8, 2, 0),
(8, 3, 0),
(8, 4, 0),
(8, 5, 0),
(8, 6, 0),
(8, 7, 0),
(8, 8, 0),
(8, 9, 0),
(8, 10, 0),
(8, 11, 0),
(8, 12, 0),
(8, 13, 0),
(9, 1, 0),
(9, 2, 0),
(9, 3, 0),
(9, 4, 0),
(9, 5, 0),
(9, 6, 0),
(9, 7, 0),
(9, 8, 0),
(9, 9, 0),
(9, 10, 0),
(9, 11, 0),
(9, 12, 0),
(9, 13, 0),
(10, 1, 0),
(10, 2, 0),
(10, 3, 0),
(10, 4, 0),
(10, 5, 0),
(10, 6, 0),
(10, 7, 0),
(10, 8, 0),
(10, 9, 0),
(10, 10, 0),
(10, 11, 0),
(10, 12, 0),
(10, 13, 0),
(11, 1, 0),
(11, 2, 0),
(11, 3, 0),
(11, 4, 0),
(11, 5, 0),
(11, 6, 0),
(11, 7, 0),
(11, 8, 0),
(11, 9, 0),
(11, 10, 0),
(11, 11, 0),
(11, 12, 0),
(11, 13, 0),
(12, 1, 0),
(12, 2, 0),
(12, 3, 0),
(12, 4, 0),
(12, 5, 0),
(12, 6, 0),
(12, 7, 0),
(12, 8, 0),
(12, 9, 0),
(12, 10, 0),
(12, 11, 0),
(12, 12, 0),
(12, 13, 0),
(13, 1, 0),
(13, 2, 0),
(13, 3, 0),
(13, 4, 0),
(13, 5, 0),
(13, 6, 0),
(13, 7, 0),
(13, 8, 0),
(13, 9, 0),
(13, 10, 0),
(13, 11, 0),
(13, 12, 0),
(13, 13, 0),
(14, 1, 0),
(14, 2, 0),
(14, 3, 0),
(14, 4, 0),
(14, 5, 0),
(14, 6, 0),
(14, 7, 0),
(14, 8, 0),
(14, 9, 0),
(14, 10, 0),
(14, 11, 0),
(14, 12, 0),
(14, 13, 0),
(15, 1, 0),
(15, 2, 0),
(15, 3, 0),
(15, 4, 0),
(15, 5, 0),
(15, 6, 0),
(15, 7, 0),
(15, 8, 0),
(15, 9, 0),
(15, 10, 0),
(15, 11, 0),
(15, 12, 0),
(15, 13, 0),
(16, 1, 0),
(16, 2, 0),
(16, 3, 0),
(16, 4, 0),
(16, 5, 0),
(16, 6, 0),
(16, 7, 0),
(16, 8, 0),
(16, 9, 0),
(16, 10, 0),
(16, 11, 0),
(16, 12, 0),
(16, 13, 0),
(17, 1, 0),
(17, 2, 0),
(17, 3, 0),
(17, 4, 0),
(17, 5, 0),
(17, 6, 0),
(17, 7, 0),
(17, 8, 0),
(17, 9, 0),
(17, 10, 0),
(17, 11, 0),
(17, 12, 0),
(17, 13, 0),
(18, 1, 0),
(18, 2, 0),
(18, 3, 0),
(18, 4, 0),
(18, 5, 0),
(18, 6, 0),
(18, 7, 0),
(18, 8, 0),
(18, 9, 0),
(18, 10, 0),
(18, 11, 0),
(18, 12, 0),
(18, 13, 0),
(19, 1, 0),
(19, 2, 0),
(19, 3, 0),
(19, 4, 0),
(19, 5, 0),
(19, 6, 0),
(19, 7, 0),
(19, 8, 0),
(19, 9, 0),
(19, 10, 0),
(19, 11, 0),
(19, 12, 0),
(19, 13, 0),
(20, 1, 0),
(20, 2, 0),
(20, 3, 0),
(20, 4, 0),
(20, 5, 0),
(20, 6, 0),
(20, 7, 0),
(20, 8, 0),
(20, 9, 0),
(20, 10, 0),
(20, 11, 0),
(20, 12, 0),
(20, 13, 0),
(21, 1, 0),
(21, 2, 0),
(21, 3, 0),
(21, 4, 0),
(21, 5, 0),
(21, 6, 0),
(21, 7, 0),
(21, 8, 0),
(21, 9, 0),
(21, 10, 0),
(21, 11, 0),
(21, 12, 0),
(21, 13, 0),
(22, 1, 0),
(22, 2, 0),
(22, 3, 0),
(22, 4, 0),
(22, 5, 0),
(22, 6, 0),
(22, 7, 0),
(22, 8, 0),
(22, 9, 0),
(22, 10, 0),
(22, 11, 0),
(22, 12, 0),
(22, 13, 0),
(23, 1, 0),
(23, 2, 0),
(23, 3, 0),
(23, 4, 0),
(23, 5, 0),
(23, 6, 0),
(23, 7, 0),
(23, 8, 0),
(23, 9, 0),
(23, 10, 0),
(23, 11, 0),
(23, 12, 0),
(23, 13, 0),
(24, 1, 0),
(24, 2, 0),
(24, 3, 0),
(24, 4, 0),
(24, 5, 0),
(24, 6, 0),
(24, 7, 0),
(24, 8, 0),
(24, 9, 0),
(24, 10, 0),
(24, 11, 0),
(24, 12, 0),
(24, 13, 0),
(25, 1, 0),
(25, 2, 0),
(25, 3, 0),
(25, 4, 0),
(25, 5, 0),
(25, 6, 0),
(25, 7, 0),
(25, 8, 0),
(25, 9, 0),
(25, 10, 0),
(25, 11, 0),
(25, 12, 0),
(25, 13, 0);